apiVersion: apps/v1
kind: Deployment
metadata:
  name: fathcv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fathcv
  template:
    metadata:
      labels:
        app: fathcv
    spec:
      containers:
      - name: fathcv-container
        image: 882314386132.dkr.ecr.ap-northeast-3.amazonaws.com/devresume:latest  # AWS ECR URI
        ports:
        - containerPort: 80  # Assuming your app listens on port 80, change if necessary
      nodeSelector:
        eks.amazonaws.com/nodegroup: WebMethod-NG  # Assuming you are deploying this app on node groups called  'WebMethod-NG' that you created
